# Generated by Django 4.0.2 on 2022-03-11 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameuser',
            name='level',
        ),
        migrations.RemoveField(
            model_name='gameuser',
            name='name',
        ),
        migrations.AddField(
            model_name='gameuser',
            name='contents',
            field=models.CharField(default='', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='gameuser',
            name='title',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
