# Generated by Django 4.0.2 on 2022-03-11 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_remove_gameuser_level_remove_gameuser_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.CharField(default='', max_length=1000, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='gameuser',
            name='repl',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.repl'),
        ),
    ]
