# Generated by Django 4.0.2 on 2022-03-11 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_repl_gameuser_repl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameuser',
            name='repl',
        ),
        migrations.AddField(
            model_name='repl',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repl', to='game.gameuser'),
        ),
    ]
